### ISSUE TITLE
Support converting to LaTeX

### ISSUE THREAD

**Issue by mabdelaal86** [frostming/marko#101]
Hi all,

I'm using marko for a while and it is really a great lib.

I have a use case where I need to convert the parsed markdown into LaTeX format. I already did that by implementing a renderer for LaTeX.

Would it worse create a pull request for supporting LaTeX format as a build in functionality in `marko`?

Thanks a lot.

**Comment by frostming** [comment]
sure, put it in the ext/ directory please
