### ISSUE TITLE
Run `pytest` locally fails

### ISSUE THREAD

**Issue by mabdelaal86** [frostming/marko#102]
Hi,

I would like to know how to run pytest for the project.
I ran `pytest test/` and `pdm run -v pytest --cov=marko/ --cov-report=xml tests`, but both failed.

I have synced the project with `pdm sync`; Should I use a different command?

I'm not familiar with `pdm`. So, sorry if my questions seem silly.
It is beneficial if there is a Makefile for most used commands, or a 'How to Contribute' document, so, beginners could easily run the most common commands.

**Comment by frostming** [comment]
Yes, the devguide is missing. But as a general suggestion when that is not available you can find it in the CI script of the project
`.git/workflows/ci.yaml`:
```bash
pdm sync -d -G toc -G codehilite
pdm run -v pytest tests
```
