### ISSUE TITLE
Issue with HTML-looking tags

### ISSUE THREAD

**Issue by md975** [frostming/marko#106]
Hi,

I'm trying to process a text coming from StackExchange in Python. It seems to be ok, except that HTML-looking tags are gone when I run 
`html=marko.convert(s)`
 e.g. 
`s=<p><em>This is an <example></em>. <example2> <a href="[LINK]">test</a></p>`
becomes
_This is an_ . test

How can I fix this and have:
`This is an <example>. <example2> test`

Thanks!

**Comment by frostming** [comment]
First the whole text is wrapped by a block HTML element `<p>` so the inner text will be kept as-is. Second, you need to escape `<example>` if you want to render it as literal text `<example>`, so the following will work:

```python
s = '<em>This is an \<example></em>. \<example2> <a href="[LINK]">test</a>'
marko.convert(s)
```
It outputs:
```
'<p><em>This is an &lt;example&gt;</em>. &lt;example2&gt; <a href="[LINK]">test</a></p>\n'
```
Which renders as:

<p><em>This is an &lt;example&gt;</em>. &lt;example2&gt; <a href="[LINK]">test</a></p>

**Comment by md975** [comment]
Thanks so much for your response. I guess my next question is not necessarily related to the library, but I'm new to this so I would really appreciate your help!
How can I escape them automatically? I have a very large text that I'm trying to process.
Is there an argument, or library that would handle this for me before rendering?
Thanks!

**Comment by frostming** [comment]
> How can I escape them automatically?

They are valid HTML tags and will be kept in the render result if not escaped properly. But you can extend Marko to customize the renderer, like so:

```python
class MyRenderer(marko.HTMLRenderer):
    tagfilter = re.compile(
        r"<(title|texarea|style|xmp|iframe|noembed|noframes|script|plaintext)",
        flags=re.I,
    )   # add more tags that you want to escape.

    def render_inline_html(self, element):
        return self.tagfilter.sub(r"&lt;\1", element.children)  # escape the left bracket '<'

markdown = marko.Markdown(renderer=MyRenderer)
markdown.convert(s)
```
