### ISSUE TITLE
Losing double backslashes, used with mathjax

### ISSUE THREAD

**Issue by sradc** [frostming/marko#116]
Hey, thanks for this library! 

I've come accross an issue where double backslashes are lost. Losing the `\\` is causing newlines to be lost in MathJax rendering.

### Minimal example to recreate:

example.md

```markdown
Example markdown

$$
y_k = [x_0, x_1,... x_{N-1}]
\begin{bmatrix}
    \exp(0)\\
    \exp(-i\frac{2 \pi k}{N})\\
    \exp(-i\frac{2 \pi k}{N}2)\\
    \exp(-i\frac{2 \pi k}{N}3)\\
    \exp(-i\frac{2 \pi k}{N}4)\\
    \vdots \\
    \exp(-i\frac{2 \pi k}{N}(N-1))
\end{bmatrix}
$$
```

convert.py

```
import marko
from pathlib import Path

infile = Path("example.md")
out = Path("example.html")
out.write_text(marko.convert(infile.read_text()))
```

example.html

```<p>Example markdown</p>
<p>$$
y_k = [x_0, x_1,... x_{N-1}]
\begin{bmatrix}
\exp(0)\
\exp(-i\frac{2 \pi k}{N})\
\exp(-i\frac{2 \pi k}{N}2)\
\exp(-i\frac{2 \pi k}{N}3)\
\exp(-i\frac{2 \pi k}{N}4)\
\vdots \
\exp(-i\frac{2 \pi k}{N}(N-1))
\end{bmatrix}
$$</p>
```

^- notice that there's now only single backslashes at the end of the lines.

---

Edit: Hmm, [cmark](https://github.com/commonmark/cmark) does the same thing..

But I think the `\\` notation works with GH pages. Not sure what I'm missing.
 
---

Edit: found `pandoc` preserves the double backslashes.

**Comment by frostming** [comment]
You need to add a custom block element wrapped by `$$` as markdown currently parses the block as normal text and unescapes the double slashes.
