### ISSUE TITLE
Running Multiple Renderers  Sequentialy

### ISSUE THREAD

**Issue by y1450** [frostming/marko#130]
First, thank you for writing  such well designed library.

I want to extract some string eg."123" from raw text element. To do so I use renderer as visitor and  extract the id and then I want to apply another renderer to render custom html.

In short, I want to one pass over the already parsed tree and then render it using custom renderer but I can not seem to work it with mixins.
eg.
``` python 
markdown = marko.Markdown()
markdown.use(extractid)
doc=markdown.parse("# aaa123 \n paragraph")
markdown.use(customrender)
markdown.convert(doc)
```
I can use a xml render and elment tree to the extraction pass over AST and render back using custom renderer but this seem to be overkill.
Is there are bettter way to implement it?

**Comment by y1450** [comment]
I managed to do it with a single render , but still  confused use of multiple render mixins. Also there are no tests the test multiple mixins.

**Comment by frostming** [comment]
Marko runs the following to build a renderer:

```
class Renderer(Mixin1, Mixin2, ..., BaseRenderer):
    pass
```
You code seems incorrect, `use` can't be called anymore after `parse`, and `convert` accepts a string instead of AST.

**Comment by frostming** [comment]
You need to call `super().xxx` in the mixin method to chain them together. But a concrete example would help.
