### ISSUE TITLE
Running Parser.parse_inline fails if Parser.parse was not invoked earlier

### ISSUE THREAD

**Issue by bluefish6** [frostming/marko#131]
Hi,

```py
import marko
marko.parser.Parser().parse_inline('*vbdfgd* dsfjfio sio `dsfs fwer `')
```

leads to:
```py
File ~/.../python3.10/site-packages/marko/inline.py:107, in LinkOrEmph.__new__(cls, match)
    106 def __new__(cls, match: "_Match") -> "LinkOrEmph":
--> 107     return parser.inline_elements[match.etype](match)

AttributeError: 'NoneType' object has no attribute 'inline_elements'
```

However:
```py
import marko
marko.parser.Parser().parse('')
marko.parser.Parser().parse_inline('*vbdfgd* dsfjfio sio `dsfs fwer `')
```
runs properly:
```py
[<marko.inline.Emphasis at 0x7f20ef920d60>,
 <marko.inline.RawText at 0x7f20f51c2140>,
 <marko.inline.CodeSpan at 0x7f20f51c0a90>]
```

After digging into code it becomes obvious as to why such behavior is observed - `marko.inline.parser` is indeed [set to `None`](https://github.com/frostming/marko/blob/master/marko/inline.py#L203-L204) (hence the error), but it's [overwritten with the Parser() instance when `Parser.parse()` is run](https://github.com/frostming/marko/blob/master/marko/parser.py#L66) (hence it works in the second snippet above).
I'm not entirely sure why this initialization was [moved from `__init__` to this place](https://github.com/frostming/marko/commit/ccdb7ef6865acca7d57f1f0d6448fd90323ba268#diff-9d793c64e18e3cd9adc2629785b1fc5801af079ffa6e1b73e32b051211a701dfL29-R75), but it seems like it should be done in [`Parser.parse_inline()`](https://github.com/frostming/marko/blob/master/marko/parser.py#L87) as well?

**Comment by frostming** [comment]
`parse_inline()` should never be called separately. It should be an internal implementation detail.

**Comment by bluefish6** [comment]
This does not seem to be mentioned [in the documentation](https://marko-py.readthedocs.io/en/latest/api.html#marko.parser.Parser.parse_inline):

![image](https://user-images.githubusercontent.com/3324881/210750134-bafc6ade-7b2f-4188-b4d8-e38420031ecf.png)

If this method is not supposed to be used publicly, maybe a good idea would be to rename it to `_parse_inline`?
