### ISSUE TITLE
v2 - parse_inline now unusable independently, errors in docs

### ISSUE THREAD

**Issue by peku33** [frostming/marko#162]
Hi, I tried updating my project from marko v1 to marko v2. I use it to parse short messages and extract just a few accepted elements (bold, italic, underline) from ast.

Previously I was able to use `Parser.parse_inline("markdown text")` to obtain children. Now this method changed it footprint to `def parse_inline(self, element: block.BlockElement, source: Source)` and its usage is not documented.

The method `parse(self, text: str)` has just the `text` parameter, but in docs its still `:param source_or_text: the text or source object.`

Is there any way to achieve previous behaviour of extracing simple elements from short string?

**Comment by frostming** [comment]
Just use the `parse(text)` method to get the parsed tree:

```python
text = "I am a **bolded text**"
doc = parse(text)
print(doc.children[0].childen)
```
