### ISSUE TITLE
Parsed links in AST

### ISSUE THREAD

**Issue by frague59** [frostming/marko#186]
Hi, 

I'm using the marko markdown parser to parse some markdown files, and use a custom renderer to generate some wagtail contents.

I'm working at AST level, using `inline.*` and `block.*` modules.

I've an issue when parsing a link `[Download document](./documents/docs.pdf)`, the inline.Link does not work as expected : the `title` attribute is always `None`.

**Comment by frostming** [comment]
it should be .label
