### ISSUE TITLE
Trailing text in AST for HTML comments and block elements

### ISSUE THREAD

**Issue by jlevy** [frostming/marko#202]
I was surprised to find:

```python
html_block = marko.parse("<!-- Comment --> with trailing text.").children[0]
print(f"{html_block} has body {html_block.body}")
```

yields

```
<HTMLBlock children=[]> has body <!-- Comment --> with trailing text.
```

Same for block elements like `<div>HTML text</div> trailing text`. It seems this is because [HTMLBlock](https://github.com/frostming/marko/blob/master/marko/block.py#L277) consumes the whole line.

This seems like a bug?

Tested with v2.1.2.

Note you don't immediately notice this when converting Markdown to HTML but it became an issue for me when converting Markdown to Markdown for normalization. Thanks for the useful library!

**Comment by frostming** [comment]
I think it's a correct translation of the [specs](https://spec.commonmark.org/0.31.2/#html-block)

You can also try it in the playground in the above web page and you will see the same result.

**Comment by jlevy** [comment]
> If the first line meets both the [start condition](https://spec.commonmark.org/0.31.2/#start-condition) and the [end condition](https://spec.commonmark.org/0.31.2/#end-condition), the block will contain just that line.

I see, you're right! This line in the spec makes for some surprising behavior 🤷 but yes Marko is correct then.
