### ISSUE TITLE
[Bug] gfm extension's task list item's RawText includes leading space

### ISSUE THREAD

**Issue by hyuri** [frostming/marko#213]
### Issue
The RawText parsed within a regular ListItem does not contain a leading space:

`- My list item` --> `Markdown` --> `My list item` (RawText)

But the RawText parsed from a gfm task list item ListItem does contain a leading space:
`- [x] My list item` --> `gfm` --> ` My list item` (RawText) — Notice the leading space before "My".

This leading space is making it more complex and bug-prone to process the ListItems, because now I have to strip the leading space of the RawText that's inside the Paragraph inside the ListItem but sometimes is inside an Emphasis inside a Paragraph inside the ListItem, and only when the ListItem contains a checkbox, so I have to either traverse the tree and strip the first RawText I find, or process everything inside the RawText capture, which adds numerous edge cases to account for.

### Proposal
Do not include the leading space in the RawText of parsed task list items. This will not only reduce complexity to users of the gfm extension, but also make it consistent with the regular parser.

Since the leading space is not actually part of the text but part of the checkbox spec, it shouldn't be included with the parsed text.

**Comment by frostming** [comment]
Again, this is consistent with the GitHub behavior.
