### ISSUE TITLE
[Change] (gfm task list) Make the "checked" property part of ListItem and not of Paragraph

### ISSUE THREAD

**Issue by hyuri** [frostming/marko#214]
### Issue
Currently, the property "checked" of gfm task list item resides inside the Paragraph inside the ListItem instead of the ListItem itself.

This makes it less intuitive and more convoluted to access the property when processing task list items:
`ListItem.children[0].checked`

Since this doesn't seem to be documented, it took me a long time to figure out the "checked" property was inside the Paragraph inside the ListItem and not the ListItem.

### Proposal
Make the "checked" property part of ListItem itself, so we can do this:
`ListItem.checked`

Since the concept of "checked" applies to a ListItem but not to a paragraph, it also makes more logical sense, which makes it more intuitive and easier to discover.

**Comment by frostming** [comment]
This is on par with the rendered HTML, the `input` element is inside the `<li>` element.

**Comment by frostming** [comment]
Especially, you can inspect the HTML of the following markdown:
```markdown
- [x] item 1
   
   second line
- [ ] item 2
```
- - -

- [x] item 1
   
   second line
- [ ] item 2

**Comment by hyuri** [comment]
It's still illogical for a Paragraph to house a "checked" property, and makes it harder to get the value. I don't see how one renderer's output is relevant to determine parser behaviour. They're independent, and not 1:1. The parser is responsible for getting the semantics of the input and delivering objects that represent that input, the renderer is responsible for displaying data.

> Especially, you can inspect the HTML of the following markdown:
> 
> ```
> - [x] item 1
>    
>    second line
> - [ ] item 2
> ```

And in the example above, "second line" is still part of the list item 1, so it should be checked too.

**Comment by frostming** [comment]
> They're independent, and not 1:1

They are apparently not independent, renderer talks to the parsed result and ideally when rendering a given element it should only see this element, not its parents. There are indeed considerations for implementation, and this is the clearest way to write the code.



> it's the renderer's job to add that leading space to the output, not the parser to the input.

Yeah that would be better but GitHub is also working in my way. Try adding more spaces and you'll see it shows in the render result.



> And in the example above, "second line" is still part of the list item 1, so it should be checked too.

But note the `input` element is a child of the `item 1` paragraph, if we move the `checked` property to the list item, how should we render `second line`?

You see, the renderer sees the parsed result and represents the tree to HTML text
