### ISSUE TITLE
[Change] Make nested List live inside List, not ListItem

### ISSUE THREAD

**Issue by hyuri** [frostming/marko#215]
### Issue
Currently, a nested List lives under a new ListItem and not directly under its parent List.

So this Markdown list:
```
- Item 1
- Item 2
    - Item 3
    - Item 4
        - Item 5
```

Parses to this object tree:

```
|_ List
    |_ ListItem
        |_ Paragraph
            |_ RawText (Item 1)
    |_ ListItem
        |_ Paragraph
            |_ RawText (Item 2)
        |_ List
            |_ ListItem
                |_ Paragraph
                    |_ RawText (Item 3)
            |_ ListItem
                |_ Paragraph
                    |_ RawText (Item 4)
                |_ List
                    |_ ListItem
                        |_ Paragraph
                            |_ RawText (Item 5)
```

This makes it harder to parse if your own model of a List stores nested Lists under the parent List itself instead of under a new ListItem under the parent List.

So, currently, to get an object tree where the nested lists live under their parent list requires an extra function to traverse down the tree and recreate the tree, and comes with new complexities to deal with.

### Proposal
House nested Lists directly under their parent Lists.

Example for the same Markdown sample list from before:
```
|_ List
    |_ ListItem
        |_ Paragraph
            |_ RawText (Item 1)
    |_ ListItem
        |_ Paragraph
            |_ RawText (Item 2)
    |_ List
        |_ ListItem
            |_ Paragraph
                |_ RawText (Item 3)
        |_ ListItem
            |_ Paragraph
                |_ RawText (Item 4)
        |_ List
            |_ ListItem
                |_ Paragraph
                    |_ RawText (Item 5)
```

For reference, that's how nested lists are structured in HTML/XHTML/XML — a List (ul/ol) lives under another List (ul/ol), not inside a ListItem (li).
So, in HTML, the same Markdown sample list from earlier would be represented as follows:
```
<ul>
    <li>Item 1</li>
    <li>Item 2</li>
    <ul>
        <li>Item 3</li>
        <li>Item 4</li>
        <ul>
            <li>Item 5</li>
        </ul>
    </ul>
</ul>
```

Notice the nested Lists live under Lists, not under ListItems.

This will make it much easier to parse for any internal models, including still allowing for models that store nested Lists under ListItems, and will even maintain consistency with HTML.

**Comment by frostming** [comment]
> House nested Lists directly under their parent Lists.

That is a wrong hierarchy. The Item 3 list belongs to the item 2 of the parent list, not parallel with Item 2, but your proposed form indicates that.

The HTML is not correct either, I just paste the markdown in github comment box and here is what it renders:

- Item 1
- Item 2
    - Item 3
    - Item 4
        - Item 5

```html
<ul>
  <li>Item 1</li>
  <li>Item 2
    <ul dir="auto">
      <li>Item 3</li>
      <li>Item 4
        <ul dir="auto">
          <li>Item 5</li>
        </ul>
      </li>
    </ul>
  </li>
</ul>
```
