### ISSUE TITLE
Inconsistent list rendering in Markdown: extra line breaks cause formatting issues in <pre> blocks.

### ISSUE THREAD

**Issue by XmasApple** [frostming/marko#217]
When using Marko to render a Markdown document and wrapping the output in a `<pre>` block, lists with empty lines (\n) between items generate additional `<p>` tags inside `<li>` elements. This breaks the formatting inside `<pre>`, making the rendering inconsistent. The inconsistency is that lists without intermediate blank lines render `<li>` elements directly, while lists with blank lines behave differently.

## Code to Reproduce:

```python
import marko

raw_md = """
list without spacings
1. no spacing between items
2. no new line appears

list with spacings
1. spacing between items

2. new_line appears

"""

markdown = marko.Markdown(renderer=marko.HTMLRenderer)
document = markdown.parse(raw_md)
rendered = markdown.render(document)

# A common post-processing step: wrapping in <pre>
print('<pre>')
print(rendered)
print('</pre>')
```

## Actual Output:

```html
<pre>
<p>list without spacings</p>
<ol>
<li>no spacing between items</li>
<li>no new line appears</li>
</ol>
<p>list with spacings</p>
<ol>
<li>
<p>spacing between items</p>
</li>
<li>
<p>new_line appears</p>
</li>
</ol>

</pre>
```

Due to extra `<p>` tags inside `<li>`, browsers interpret the rendered HTML inconsistently within the `<pre>` block, breaking the formatting.
<img width="288" alt="image" src="https://github.com/user-attachments/assets/dd5ef0a8-8f78-423f-8ca6-4134211479b8" />

## Expected Behavior:
I expected the list rendering to remain consistent — regardless of whether empty lines are present between list items — so that the `<pre>` formatting stays correct. For example, the desired result would be:

```html
<pre>
<p>list without spacings</p>
<ol>
<li>no spacing between items</li>
<li>no new line appears</li>
</ol>
<p>list with spacings</p>
<ol>
<li><p>spacing between items</p></li>
<li><p>new_line appears</p></li>
</ol>
</pre>
```
Here we see the `<li>` elements do not contain inner `<p>` tags.

<img width="275" alt="image" src="https://github.com/user-attachments/assets/5d6495c2-1d9d-4fe3-a91f-4c0abbc85cd9" />

**Comment by frostming** [comment]
This is clarified in the CommonMark spec: https://arc.net/l/quote/jpselbty

Also try rendering the markdown in GitHub comment box and it will give the same result.

All are expected.
