### ISSUE TITLE
Can I know how to use an Extension with the CLI version of Marko?

### ISSUE THREAD

**Issue by phtan** [frostming/marko#52]
I have read in the docs that one can use an Extension (for example, FootnoteExtension), like so:

```
from marko import Markdown
from marko.ext.footnote import FootnoteExtension
# Add footnote extension
markdown = Markdown(extensions=[FootnoteExtension])
markdown.use(FootnoteExtension)

text = "Here is a link to a footnote[^1] \n\n[^1]: Footnote here"
print(markdown(text))
```

That works as expected - that is, if I type the above commands into an interactive Python interpreter/shell.

However, what if I want to use the CLI version of Marko, with FootnoteExtension?

An example of a use case (in which I type the below command into a Command Prompt, instead of a Python interpreter/shell)

```
$ cat arbitrary_text_with_footnote.md | marko > is_footnote_here.html
```

I expected that a footnote appears in is_footnote_here.html . However, it seems that a footnote does not appear.

May I know how I can use the CLI version of Marko, with FootnoteExtension?

**Comment by frostming** [comment]
Thanks for the request. It hasn't been implemented yet, but I think it isn't difficult to add support. I can implement it., or any PR is welcomed.

**Comment by phtan** [comment]
I see. Got it.

Let me think if I can spare the resources to attempt a PR.

If you don't hear from me, that means I decided not to attempt a PR :-)
