### ISSUE TITLE
Ordered lists starting at number not equal to 1 are not identified as lists in paragraphs

### ISSUE THREAD

**Issue by inkychris** [frostming/marko#60]
The following example does not get parsed correctly:
```markdown
line 1:
2. item 1
3. item 2
```
### Steps to reproduce:
```python
>>> import marko
>>> marko.convert('line 1:\n2. item 1\n3. item 2')
```
#### Expected:
```
'<p>line 1:</p>\n<ol start="2">\n<li>item 1</li>\n<li>item 2</li>\n</ol>\n'
```

#### Actual:
```
'<p>line 1:\n2. item 1\n3. item 2</p>\n'
```

### Solution:
It appears that the issue lies in [`block.Paragraph.break_paragraph`](https://github.com/frostming/marko/blob/cc6d5779d95e6a515c2135405de047aa6c5361a5/marko/block.py#L376):
```python
if parser.block_elements["List"].match(source):
    result = parser.block_elements["ListItem"].parse_leading(source.next_line())
    if lazy or (result[1][:-1] == "1" or result[1] in "*-+") and result[3]:
        return True
```
I believe that `result[1][:-1] == "1"` should instead be `result[1][:-1].isdigit()` or similar. Note that this change was used to generate the expected output above.

**Comment by frostming** [comment]
The behavior is described in Commonmark's spec:
>Exceptions:
>
>When the first list item in a list interrupts a paragraph—that is, when it starts on a line that would otherwise count as paragraph continuation text—then (a) the lines Ls must not begin with a blank line, and (b) if the list item is ordered, the start number must be 1.
If any line is a thematic break then that line is not a list item.

Or you can just try in Github's markdown editor to see what it is rendered.
