### ISSUE TITLE
Renderer mixins targetting multiple renderer base classes

### ISSUE THREAD

**Issue by benhowes** [frostming/marko#70]
I have just been making an extension which is to be used in a markdown -> markdown usecase, so my render mixins will produce markdown. I may also want to produce HTML output too though.

Perhaps the mixin can determine it's parent, e.g.:

```python
class RenderMixin:

    def render_code_block(self, element):
        if isinstance(self, HTMLRenderer):
             return "<code><pre>...."
        elif isinstance(self, MarkdownRenderer):
            return "```\n...."
        raise NotImplemented()
```

Do you have any thoughts on this, or another pattern in mind?

**Comment by frostming** [comment]
The mixin pattern doesn't set limit on how  ppl use it. Of course you can achieve what you want by checking the type of `self` like this. Although it doesn't looks a good idea to me to do more than one thing in a mixin.

**Comment by benhowes** [comment]
Sure, I get you. 

> Although it doesn't looks a good idea to me to do more than one thing in a mixin.

This is the crux of why I raised this.

Do you have plans to make the built in extensions compatible with the `MarkdownRenderer` for example?

**Comment by frostming** [comment]
Oh, I understand what you want. I think, but not tried that if you don't include those extensions, `MarkdownRenderer` can render markdown correctly for you.

**Comment by benhowes** [comment]
I don't know that we were quite understanding each other here. Ultimately, I think it would be nice if extensions can support more than one base renderer with a standard pattern which is endorsed by the package maintainer. But, it's also not blocking me from my current use case.  

Feel free to close this if you don't see it as being important :)

**Comment by frostming** [comment]
Yes, the proposed solution or any possible approach seems a bit weird to me. IMO it violates [S - Single-responsiblity Principle][1] and [O - Open-closed Principle][2].

[1]: https://www.digitalocean.com/community/conceptual_articles/s-o-l-i-d-the-first-five-principles-of-object-oriented-design#single-responsibility-principle
[2]:https://www.digitalocean.com/community/conceptual_articles/s-o-l-i-d-the-first-five-principles-of-object-oriented-design#open-closed-principle
