### ISSUE TITLE
HTML entity references are not expanded in AST

### ISSUE THREAD

**Issue by IRDonch** [frostming/marko#76]
```
$ marko -r marko.ast_renderer.ASTRenderer <(echo '&lt;&#42;')
{'link_ref_defs': {}, 'children': [{'children': [{'children': '&lt;&#42;', 'element': 'raw_text'}], 'element': 'paragraph'}], 'element': 'document'}
```

The children of the `raw_text` element should be `<*`, not `&lt;&#42;`, because that's the actual text of the document.

**Comment by frostming** [comment]
wait why? the markdown text you gave is `&lt;&#42` should be rendered as it is.

See this: https://spec.commonmark.org/dingus/?text=%20%20%09foo%09baz%09%09bim%0A
