### ISSUE TITLE
Tables in AST Results 

### ISSUE THREAD

**Issue by cytwill** [frostming/marko#78]
I found that markdown tables are not included in the current AST elements. So I am wondering if this extension would be implemented recently?

**Comment by frostming** [comment]
table element is not included in standard commonmark but in the github flavored markdown, try this:
```python
from marko.ext.gfm import GFM
from marko import Markdown
from marko.ast_renderer import ASTRenderer

markdown = Markdown(renderer=ASTRenderer)
markdown._extra_elements.extend(GFM.elements)
markdown.convert(text)
```

**Comment by cytwill** [comment]
Sure, thanks for answering!
