### ISSUE TITLE
Have renderer join the lines of a paragraph?

### ISSUE THREAD

**Issue by lebigot** [frostming/marko#79]
Thanks for this library! It looks quite robust. :)

What is the **best way** to **join the lines of a paragraph** (unless a line ends with two blank spaces, as per the Markdown specs)? For example, the following source:
```
First sentence.
Second sentence.
```
should be rendered as
```
First sentence. Second sentence.
```

The use case is a converter from Markdown to a markup language where line breaks are represented as line breaks (I use an extension to md_renderer.MarkdownRenderer, for this). It wouldn't make sense to have line breaks in the source (again when not preceded by two blank spaces) to produce line breaks in the output.

I can't find any hint in the documentation, or even in the code.

PS: in the same spirit, what is the best way to have **lines ending with two spaces** simply be rendered as the **source line but without the last two spaces**? The line break in the target markup language are, again, interpreted verbatim, so what is needed is to simply keep the line break.

**Comment by frostming** [comment]
Do you mean to keep the soft break (line breaks that do not break the paragraph) in the AST result?

**Comment by frostming** [comment]
You can just subclass `md_renderer.MarkdownRenderer` and change the rendering behavior of `LineBreak`:
https://github.com/frostming/marko/blob/d9cdb178e1febe3d9fbf25d4e726af9e7819af6b/marko/md_renderer.py#L144-L145

and write your own logic when `soft == True`

**Comment by lebigot** [comment]
This is perfect. Thank you for you help.

I had missed this `render_line_break()` at the end of `md_renderer.py`.

I continue to really appreciate how flexible and clean marko is: keep up the good work!
