### ISSUE TITLE
Anchors in github flavored markdown

### ISSUE THREAD

**Issue by hroskes** [frostming/marko#83]
When you put a header in a markdown document on github, github puts an html anchor at that position, and you can link to it.  For example: https://github.com/frostming/marko#why-marko.  I would really like an extension that can puts these anchors in HTML.

**Comment by frostming** [comment]
Why not?

It is already shipped with Marko!
Try here: https://marko-py.readthedocs.io/en/latest/extensions.html#toc-extension

**Comment by hroskes** [comment]
Oh, I see!  Thank you!
