### ISSUE TITLE
Table parsing error

### ISSUE THREAD

**Issue by liushilive** [frostming/marko#85]
code:

```python
from marko.ext.gfm import gfm

gfm("""symbol | describe
:---:|---
`!`  | not
`&&`、`-a` | and
`||`、`-o` | or
""")
```

Actual Out:

```html
<table>\n<thead>\n<tr>\n<th align="center">symbol</th>\n<th>describe</th>\n</tr>\n</thead>\n<tbody>\n<tr>\n<td align="center"><code>!</code></td>\n<td>not</td>\n</tr>\n<tr>\n<td align="center"><code>&amp;&amp;</code>、<code>-a</code></td>\n<td>and</td>\n</tr>\n<tr>\n<td align="center">`</td>\n<td></td>\n</tr>\n</tbody></table>
```

Actual Priview:

<table><thead><tr><th align="center">symbol</th><th>describe</th></tr></thead><tbody><tr><td align="center"><code>!</code></td><td>not</td></tr><tr><td align="center"><code>&amp;&amp;</code>、<code>-a</code></td><td>and</td></tr><tr><td align="center">`</td><td></td></tr></tbody></table>

Desired Out:

```html
<table>\n<thead>\n<tr>\n<th align="center">symbol</th>\n<th>describe</th>\n</tr>\n</thead>\n<tbody>\n<tr>\n<td align="center"><code>!</code></td>\n<td>not</td>\n</tr>\n<tr>\n<td align="center"><code>&amp;&amp;</code>、<code>-a</code></td>\n<td>and</td>\n</tr>\n<tr>\n<td align="center"><code>||</code>、<code>-o</code></td>\n<td>or</td>\n</tr>\n</tbody></table>
```

Desired Priview:

<table><thead><tr><th align="center">symbol</th><th>describe</th></tr></thead><tbody><tr><td align="center"><code>!</code></td><td>not</td></tr><tr><td align="center"><code>&amp;&amp;</code>、<code>-a</code></td><td>and</td></tr><tr><td align="center"><code>||</code>、<code>-o</code></td><td>or</td></tr></tbody></table>

**Comment by frostming** [comment]
This is not a bug, block elements are always parsed before inline elements, so` |` inside the backticks are recognized as the cell delimiter. You can paste the markdown code to the comment box(where GFM is used, officially) to see the preview.
