### ISSUE TITLE
Table support

### ISSUE THREAD

**Issue by hawkfish** [frostming/marko#89]
It looks like `marko` does not parse tables:

```txt
|Header1 |Header2  | Header3|
--- | --- | ---
|data1|data2|data3|
|data11|data12|data13|
```
produces
```html
<p>|Header1 |Header2  | Header3|
--- | --- | ---
|data1|data2|data3|
|data11|data12|data13|</p>
```

Is that something that is planned?

**Comment by frostming** [comment]
It's a thing of github flavored markdown, not CommonMark. Take the `gfm` object instead:

```python
from marko.ext.gfm import gfm
print(gym(text))
```

**Comment by hawkfish** [comment]
Ah, sorry. I just saw a question on StackOverflow so I added it to `textform` when I couldn't find any package that supported it.
