### ISSUE TITLE
string labels, arbitrary IDs for footnotes

### ISSUE THREAD

**Issue by jakekara** [frostming/marko#94]
Hi, I'm new to this code base, but I've been using Marko for a while and find it very handy. Here's an idea for a possible new feature.

I created an alternative footnotes plugin called labeled_footnotes, which allows footnotes to have arbitrary strings, rather than just numerical indexes as their IDs. This makes the anchor link URL fragments more meaningful, and allows for non-numerical footnote labels.

I have taken that a step further. I have a use a case where I need to specify arbitrary display labels for footnotes that differ from their unique IDs.

My solution has been to support the following syntax. In place of the footnote ref and def, instead of just doing `[^1]` you can use `[^one]` or `[^1=Footnote 1]`.

Here's an example input:

```markdown
This is some example text with a footnote [^10=Footnote]. 

[^10=Footnote]: A footnote is a thing that adds more detail as an aside to the main text.
```

Which would generate the following output: 

```html
<p>This is some example text with a footnote <sup class="footnote-ref" id="fnref-10"><a href="#fn-10">Footnote</a></sup>. </p>
<div class="footnotes">
<ol>
<li id="fn-10" data-label="Footnote">
<p>A footnote is a thing that adds more detail as an aside to the main text.<a href="#fnref-10" class="footnote">&#8617;</a></p></li>
</ol>
</div>
```

Here's the branch in my forked repo: [https://github.com/jakekara/marko/tree/labeled-footnotes](https://github.com/jakekara/marko/tree/labeled-footnotes).

**Comment by frostming** [comment]
it is nice! you can ship it as a separate package. Should be easy to be plugged in.

**Comment by jakekara** [comment]
Great! I will do that when I have some time next.

**Comment by jakekara** [comment]
Update: I had time to make a separate package here: [https://github.com/jakekara/marko-labeled-footnotes](https://github.com/jakekara/marko-labeled-footnotes)
