### ISSUE TITLE
Querying BlockElement types

### ISSUE THREAD

**Issue by ishigoya** [frostming/marko#96]
Hello,

I've been using marko for a little while now and I've found it really useful, so thanks!

I'm trying to parse a markdown document, and then conditionally render it in markdown. One example would be rendering only the headings of a document.

At present, information about the type of each block is in the Python object type itself, but there is no other way to access it. If I wanted to iterate over headings, I would have to do something like:

```python
[x for x in doc.children if "Heading" in str(type(x))]
```

One way around this would be to add a function to the `BlockElement` class that returns the class name. That way, it wouldn't be necessary to query to object type directly.

What do you think?

**Comment by frostming** [comment]
I think `isinstance` check would be better

**Comment by ishigoya** [comment]
Like this?

```python
[x for x in doc.children if isinstance(x, marko.block.Heading)]
```

This requires thinking about the import (using `import marko`, importing `Heading` directly, etc), which seems like unnecessary work when the goal is just to check the type of a markdown element.

Ideally, I'd like to be able to do something like this:

```python
[x for x in doc.children if x.element_type == "Heading"]
```

and get the type through an attribute or a function of the object.

It's unusual not to be able to get information representing an object through its API, but I recognise that in this case, the Python object type is very tightly linked to the markdown element type!

**Comment by frostming** [comment]
It is possibly useful, I am okay if you can make the change and submit a PR :)
